from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from datetime import datetime
import tempfile


def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    canvas.drawRightString(580, 20, text)


def generate_pdf(report_text,
                 severity_chart=None,
                 type_chart=None,
                 ml_chart=None,
                 logo_path=None):

    styles = getSampleStyleSheet()

    tmp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf_path = tmp_pdf.name

    story = []

    # ------------------------------------------------
    # Header / Title
    # ------------------------------------------------

    if logo_path:
        story.append(Image(logo_path, width=120, height=50))
        story.append(Spacer(1, 10))

    story.append(Paragraph("Dark Web Threat Intelligence Report", styles["Title"]))
    story.append(Spacer(1, 10))

    date = datetime.now().strftime("%B %d, %Y")

    story.append(Paragraph(f"<b>Generated:</b> {date}", styles["Normal"]))
    story.append(Spacer(1, 20))

    # ------------------------------------------------
    # Executive Summary
    # ------------------------------------------------

    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph(report_text.replace("\n", "<br/>"), styles["BodyText"]))
    story.append(Spacer(1, 30))

    # ------------------------------------------------
    # Charts Section
    # ------------------------------------------------

    story.append(Paragraph("Threat Analysis Charts", styles["Heading2"]))
    story.append(Spacer(1, 20))

    if ml_chart:
        story.append(Paragraph("ML Threat Classification Distribution", styles["Heading3"]))
        story.append(Image(ml_chart, width=5*inch, height=3*inch))
        story.append(Spacer(1, 20))

    if severity_chart:
        story.append(Paragraph("Threat Severity Distribution", styles["Heading3"]))
        story.append(Image(severity_chart, width=5*inch, height=3*inch))
        story.append(Spacer(1, 20))

    if type_chart:
        story.append(Paragraph("Threat Type Distribution", styles["Heading3"]))
        story.append(Image(type_chart, width=5*inch, height=3*inch))

    story.append(PageBreak())

    # ------------------------------------------------
    # Footer section
    # ------------------------------------------------

    story.append(Paragraph("System Information", styles["Heading2"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph(
        "This report was automatically generated by the Dark Web Threat Monitoring System. "
        "The system continuously crawls dark web sources using Tor, analyzes content using "
        "hybrid rule-based and machine learning techniques, and identifies potential cyber threats.",
        styles["BodyText"]
    ))

    story.append(Spacer(1, 20))

    story.append(Paragraph(
        "Machine Learning Model: DarkBERT Transformer<br/>"
        "Detection Engine: Hybrid Rule + ML Classification<br/>"
        "Visualization: Streamlit Dashboard",
        styles["BodyText"]
    ))

    doc = SimpleDocTemplate(pdf_path, pagesize=letter)

    doc.build(
        story,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number
    )

    return pdf_path